prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> delete { <http://db.uwaterloo.ca/~galuc/wsdbm/Product22535> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product22535> } insert { auction:906-Product22535-94 auction:bid '94'^^xsd:integer ; auction:sponsor wsdbm:User0 ; ?p1 ?o1 ; owl:sameAs <http://db.uwaterloo.ca/~galuc/wsdbm/Product22535> . ?s2 ?p2 auction:906-Product22535-94. } where { <http://db.uwaterloo.ca/~galuc/wsdbm/Product22535> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product22535> }
