prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> delete { <http://db.uwaterloo.ca/~galuc/wsdbm/Product16075> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product16075> } insert { auction:995-Product16075-5 auction:bid '5'^^xsd:integer ; auction:sponsor wsdbm:User0 ; ?p1 ?o1 ; owl:sameAs <http://db.uwaterloo.ca/~galuc/wsdbm/Product16075> . ?s2 ?p2 auction:995-Product16075-5. } where { <http://db.uwaterloo.ca/~galuc/wsdbm/Product16075> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product16075> }
