prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> delete { <http://db.uwaterloo.ca/~galuc/wsdbm/Product13219> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product13219> } insert { auction:967-Product13219-33 auction:bid '33'^^xsd:integer ; auction:sponsor wsdbm:User0 ; ?p1 ?o1 ; owl:sameAs <http://db.uwaterloo.ca/~galuc/wsdbm/Product13219> . ?s2 ?p2 auction:967-Product13219-33. } where { <http://db.uwaterloo.ca/~galuc/wsdbm/Product13219> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product13219> }
