prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> delete { <http://db.uwaterloo.ca/~galuc/wsdbm/Product6618> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product6618> } insert { auction:909-Product6618-91 auction:bid '91'^^xsd:integer ; auction:sponsor wsdbm:User0 ; ?p1 ?o1 ; owl:sameAs <http://db.uwaterloo.ca/~galuc/wsdbm/Product6618> . ?s2 ?p2 auction:909-Product6618-91. } where { <http://db.uwaterloo.ca/~galuc/wsdbm/Product6618> ?p1 ?o1 . ?s2 ?p2 <http://db.uwaterloo.ca/~galuc/wsdbm/Product6618> }
