prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
prefix purl: <http://www.purl.org/>
prefix auction: <http://www.example.auction.org/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select (coalesce(?tag, ?product) as ?link) ?bid where {
  ?product rdf:type wsdbm:ProductCategory11
  optional {
    ?product auction:bid ?bid;
      owl:sameAs ?tag
  }
} order by ?bid
