prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
prefix auction: <http://www.example.auction.org/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

delete {
    wsdbm:Product0 ?p1 ?o1 .
    ?s2 ?p2 wsdbm:Product0 .
}

insert {
  auction:0001 auction:bid "30"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    ?p1 ?o1 ;
    owl:sameAs wsdbm:Product0 .
  ?s2 ?p2 auction:0001 .
}

where {
  wsdbm:Product0 ?p1 ?o1 .
  ?s2 ?p2 wsdbm:Product0 .
}
