prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
prefix purl: <http://www.purl.org/>
prefix auction: <http://www.example.auction.org/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

insert data {
  wsdbm:Product0 auction:bid "30"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0001.

  wsdbm:Product10287 auction:bid "20"^^xsd:integer ;
    auction:sponsor wsdbm:User;
    owl:sameAs auction:0002.

  wsdbm:Product10488 auction:bid "100"^^xsd:integer ;
    auction:sponsor wsdbm:User;
    owl:sameAs auction:0003.

  wsdbm:Product1 auction:bid "17"^^xsd:integer ;
    auction:sponsor wsdbm:User;
    owl:sameAs auction:0004.

  wsdbm:Product12111 auction:bid "48"^^xsd:integer ;
    auction:sponsor wsdbm:User;
    owl:sameAs auction:0005.
  wsdbm:Product10663 auction:bid "77"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0006.

  wsdbm:Product12728 auction:bid "11"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0007.

  wsdbm:Product1574 auction:bid "28"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0008.

  wsdbm:Product18361 auction:bid "61"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0009.

  wsdbm:Product20015 auction:bid "2"^^xsd:integer ;
    auction:sponsor wsdbm:User10039 ;
    owl:sameAs auction:0000.

}
