prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
prefix auction: <http://www.example.auction.org/>
prefix owl: <http://www.w3.org/2002/07/owl#>


insert data {
  wsdbm:Product10287 auction:bid '20' ;
    auction:sponsor wsdbm:User;
    owl:sameAs auction:0001.
}
