SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://purl.org/stuff/rev#hasReview> ?v3 .  ?v1 <http://schema.org/contentSize> ?v9 .  ?v3 <http://purl.org/stuff/rev#rating> ?v4 .  ?v3 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v3 <http://purl.org/stuff/rev#text> ?v6 .  ?v3 <http://purl.org/stuff/rev#title> ?v7 .  ?v3 <http://purl.org/stuff/rev#totalVotes> ?v8 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://purl.org/stuff/rev#hasReview> ?v3 .  ?v1 <http://schema.org/contentSize> ?v9 .  ?v3 <http://purl.org/stuff/rev#rating> ?v4 .  ?v3 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v3 <http://purl.org/stuff/rev#text> ?v6 .  ?v3 <http://purl.org/stuff/rev#title> ?v7 .  ?v3 <http://purl.org/stuff/rev#totalVotes> ?v8 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://purl.org/stuff/rev#hasReview> ?v3 .  ?v1 <http://schema.org/contentSize> ?v9 .  ?v3 <http://purl.org/stuff/rev#rating> ?v4 .  ?v3 <http://purl.org/stuff/rev#reviewer> ?v5 .  ?v3 <http://purl.org/stuff/rev#text> ?v6 .  ?v3 <http://purl.org/stuff/rev#title> ?v7 .  ?v3 <http://purl.org/stuff/rev#totalVotes> ?v8 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#title> ?v1 .  ?v0 <http://schema.org/caption> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory3> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v2 .  ?v3 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://ogp.me/ns#title> ?v4 .  ?v1 <http://schema.org/expires> ?v7 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  ?v3 <http://ogp.me/ns#tag> ?v2 .  ?v3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v6 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory7> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory5> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://schema.org/contentRating> ?v2 .  ?v0 <http://schema.org/description> ?v3 .  ?v0 <http://schema.org/expires> ?v4 .  ?v0 <http://schema.org/text> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://ogp.me/ns#tag> ?v2 .  ?v1 <http://schema.org/contentRating> ?v6 .  ?v1 <http://schema.org/description> ?v7 .  ?v1 <http://schema.org/keywords> ?v8 .  ?v1 <http://schema.org/text> ?v9 .  ?v1 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v4 .  ?v10 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v1 .  ?v4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/contentRating> ?v3 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/subscribes> ?v1 .  ?v4 <http://db.uwaterloo.ca/~galuc/wsdbm/gender> ?v5 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory8> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory6> .  ?v0 <http://xmlns.com/foaf/homepage> ?v1 .  ?v0 <http://schema.org/expires> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory14> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory11> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v0 <http://purl.org/goodrelations/validThrough> ?v2 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory2> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory10> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory1> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/keywords> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory4> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory13> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  }
SELECT * WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory0> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://schema.org/contentRating> ?v5 .  ?v0 <http://schema.org/contentSize> ?v6 .  ?v0 <http://schema.org/description> ?v7 .  ?v8 <http://db.uwaterloo.ca/~galuc/wsdbm/likes> ?v0 .  ?v2 <http://ogp.me/ns#tag> ?v1 .  ?v2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v4 .  }
SELECT * WHERE {  ?v1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory9> .  ?v0 <http://purl.org/goodrelations/includes> ?v1 .  ?v1 <http://schema.org/text> ?v3 .  }
