SELECT (coalesce( ?altid, ?v0 ) as ?link) ?v3 ?v1 WHERE {  ?v0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://db.uwaterloo.ca/~galuc/wsdbm/ProductCategory12> .  ?v0 <http://ogp.me/ns#tag> ?v1 .  ?v0 <http://db.uwaterloo.ca/~galuc/wsdbm/hasGenre> ?v3 .  optional { ?v0  <http://auction.example.org/bid> ?bid; <http://www.w3.org/2002/07/owl#sameAs> ?altid } } order by ?bid
