prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> insert data { <http://db.uwaterloo.ca/~galuc/wsdbm/Product24094> auction:bid '61'^^xsd:integer ; auction:sponsor wsdbm:User0 ; owl:sameAs auction:658-Product24094-61. }
