prefix wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/> prefix auction: <http://auction.example.org/> prefix owl: <http://www.w3.org/2002/07/owl#> prefix xsd: <http://www.w3.org/2001/XMLSchema#> insert data { <http://db.uwaterloo.ca/~galuc/wsdbm/Product11628> auction:bid '74'^^xsd:integer ; auction:sponsor wsdbm:User0 ; owl:sameAs auction:654-Product11628-74. }
